/* eslint-disable @typescript-eslint/camelcase */
const sample = {
    skipForm: 'false',
    hasLeadCapture: 'true',
    conf_page: 'https://hosted-scratch.herokuapp.com/trial?template=https://github.com/mshanemc/platformTrial',
    startPage: '/form/signup/freetrial-platform',
    successPage: 'https://hosted-scratch.herokuapp.com/trial?template=https://github.com/mshanemc/platformTrial',
    failPage: 'https://hosted-scratch.herokuapp.com/trial?template=https://github.com/mshanemc/platformTrial',
    resultWebApp: '/',
    process_form: 'true',
    landing_page: '/form/signup/freetrial-platform',
    FormCampaignId: '7010M000000nQr6',
    DriverCampaignId: '70130000000sUVq',
    DefaultDriverCampaignId: '70130000000CrZx',
    'Lead.Primary_Product_Interest__c': 'App Cloud',
    mcloudSiteId: '2761',
    mcloudCookieWrite: '0',
    mcloudCustomerGUID: '',
    CM_OMTRJoinID: '7010M000000nQr6QAE|bc74b30b773a1e4b30dccfb14538b2241dd6c3fb',
    'Lead.LeadSource': 'Organic Search',
    mcloudFormName: 'GLOB_MAIN_T2L1_OCMS_LCS1',
    mcloudHandlingInstructions: '',
    'Lead.LeadType__c': '',
    'CampaignMember.Offers__c': '',
    Domain_Site: 'www.salesforce.com',
    amo_efid: 'Cj0KCQiA2ITuBRDkARIsAMK9Q7NsEFm4IwJpuBM3_bflHIzJybGeV9k1ZSsTn7rYvi_xJ_gz1GmE87gaAuvvEALw_wcB:G:s',
    PartnerPromoCode: '',
    UserFirstName: 'Reginald',
    UserLastName: 'Testaforma',
    UserTitle: 'QA Specialist ',
    UserEmail: 'reggie@shaneformtesting.org',
    userNameErrMsg: 'This email is already in use. Try another.',
    UserPhone: '7850484333',
    CompanyName: 'Shanes form testing, ltd',
    CompanyEmployees: '10',
    CompanyCountry: 'US',
    CompanyState: 'Texas',
    CompanyPostalCode: '77355',
    SubscriptionAgreement: 'on',
    Region__c: ''
};

export { sample };
